version: '3.8'

services:
  form-backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - form-data:/app/data
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: always

volumes:
  form-data:
